Table bill page
marcoshenriqueb/epraja pull request #7
Opened 2018-04-03 16:44 UTC by joaovbalmeida

2018-04-03 18:30 UTC, marcoshenriqueb requested changes

2018-04-03 18:30 UTC, marcoshenriqueb commented on src/app/pages/items/items.js
> +    console.log(this.state.activeFilters);
Remover

2018-04-03 18:30 UTC, marcoshenriqueb commented on src/app/pages/table/table.js
> +    return '';
Essa função toda pode virar o seguinte:

```
return button === this.state.filter ? 'secondary' : '';
```

2018-04-03 18:30 UTC, marcoshenriqueb commented on src/app/pages/table/table.js
> +    if (!Object.keys(this.getTable()).length) return [];
Tenta melhorar sempre a organização do código p facilitar a leitura. Pula uma linha dps desse if por exemplo.

2018-04-03 18:30 UTC, marcoshenriqueb commented on src/app/pages/table/table.js
> +      const itemsQty = [];
Não gosto muito da ideia de usar dois arrays separados para type e qty não. Preferia que fosse um array só com objetos. Assim parece ter mais espaço para erro. Mas se está funcionando, ok.

2018-04-03 18:41 UTC, joaovbalmeida commented on src/app/pages/table/table.js
> +      const itemsQty = [];
é pq isso facilita na hora de procurar um index de um elemento, se eu fizesse um array só, teria que por a quantidade como um atributo do itemsType, e ai na hora de fazer a busca do index, teria q procurar um atributo dentro de um objeto do array, no lugar de so procurar uma string em um array

2018-04-03 18:48 UTC, marcoshenriqueb approved these changes

2018-04-04 00:04 UTC, marcoshenriqueb approved these changes

2018-04-04 00:04 UTC, merged